name: Build and Deploy to Dev, QA, and Prod

on:
  push:
    branches:
      - main     # Trigger on push to main (Prod)
      - staging  # Trigger on push to staging (QA)
      - dev      # Trigger on push to dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Set up .NET 8'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 'Build with dotnet'
        run: dotnet build --configuration Release

      - name: 'Publish with dotnet'
        run: dotnet publish -c Release -o ./publish
        
      - name: 'Upload artifact for deployment'
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./publish

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/dev' # Only run this job for the 'dev' branch
    
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          
      - name: 'Deploy to Azure (Dev Slot)'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'quickfeedback-app' # Your main app name
          slot-name: 'dev'                # Deploy to the 'dev' slot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_DEV }}
          package: '.'

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/staging' # Only run this job for the 'staging' branch
    
    environment:
      name: 'Staging'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          
      - name: 'Deploy to Azure (Staging Slot)'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'quickfeedback-app' # Your main app name
          slot-name: 'staging'            # Deploy to the 'staging' slot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_QA }}
          package: '.'

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' # Only run this job for the 'main' branch
    
    # This adds a manual approval gate before deploying to production
    environment:
      name: 'Production' 
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          
      - name: 'Deploy to Azure (Production Slot)'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'quickfeedback-app' # Your main app name
          # No slot-name means it deploys to the 'production' slot
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_PROD }}
          package: '.'
